#ifndef CCALC_STATUS_H
#define CCALC_STATUS_H

typedef enum {
    OK,
    OUT_OF_MEMORY,
    UNEXPECTED_CHARACTER,
    INVALID_EXPONENT,
    UNKNOWN_FUNCTION_OR_CONSTANT,
    STACK_UNDERFLOW,
    STACK_NOT_EMPTY,
    UNKNOWN_CONSTANT,
    UNHANDLED_OPERATOR,
    UNHANDLED_FUNCTION,
    UNHANDLED_TOKEN_TYPE,
    UNEXPECTED_END_OF_INPUT,
    UNEXPECTED_TEXT_AT_END,
    UNMATCHED_PARENTHESIS,
    UNEXPECTED_OPERATOR,
    MISSING_LEFT_PARENTHESIS,
    MISSING_FUNCTION_ARGUMENT,
} status;

extern const char *status_messages[];

#endif
